spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./data/devDb # In-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  h2:
    console:
      enabled: true       # Enable web console
      path: /h2-console   # Access URL
      settings:
        web-allow-others: true  # Allow remote access
        
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update    # Schema management
    show-sql: true
  
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    clear-checksums: true

eureka:
  instance:
    prefer-ip-address: false  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
