server:
  port: 8081
spring:
  application:
    name: intern-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  
  liquibase:
    enabled: false   
