
server:
  port: 8084
spring:
  application:
    name: supervisor-service
  
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
  
  liquibase:
    enabled: false   
    
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
